### PR TITLE
Update blockdesign to new Vivado 2021.2

### PR DESCRIPTION
**Pull request by jonschumacher**
Warning: I only tried if this synthesizes, but not if all functions of the image are running, since I do not have the broad image of all the functions anymore.

### CODE REVIEW

**Comment by tknopp** [comment]
I once tried this and the image simply did not work. But I am open to retry.

**Comment by jonschumacher** [comment]
I see. The design has negative slack. I will try to figure it out when I have time. Converting to draft for the moment.

**Comment by tknopp** [comment]
does this work?

**Comment by jonschumacher** [comment]
Not yet. I was able to fix all negative slacks except for the trapezoid part of the signal generator. Then I will test again within my RP setup and ping you to check if this is also working for you.

**Comment by jonschumacher** [comment]
For me, the generated image works. Could you please check with your system?

**Comment by jonschumacher** [comment]
All changes from this PR are also in #35, but #35 also includes a significant change of the build system. Thus, I close this PR in favor of the other one.

**Pull request closed without merging**
